apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: spring
spec:
  replicas: 3
  activeDeadlineSeconds: 120
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: java-deployment
        image: stephanoumenos/java-deployment
        ports:
          - containerPort: 8080
