apiVersion: batch/v1
kind: Job
metadata:
  name: java-deployment
  labels:
    app: spring
spec:
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: java-deployment
        image: stephanoumenos/java-deployment
        ports:
          - containerPort: 8080
      restartPolicy: Never
