apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
          - name: nginx-conf
            mountPath: /etc/nginx/conf.d
          - name: ssl-certificates
            mountPath: /etc/nginx/certificates/
            readOnly: true
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items: 
            - key: nginx.conf
              path: default.conf
      - name: ssl-certificates
        secret:
            secretName: ssl-certificates
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  type: LoadBalancer
  loadBalancerIP: 192.168.99.105
