apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-deployment
  labels:
    app: spring
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - name: java-deployment
        image: stephanoumenos/java-deployment
        ports:
          - containerPort: 8080
---
kind: Service
apiVersion: v1
metadata:
  name: spring-service
spec:
  selector:
    app: spring
  ports:
  - protocol: TCP
    port: 8080
  # Proxy forwarding through NGINX now
  # type: LoadBalancer
  # loadBalancerIP: 192.168.99.108
